// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN


#include "telegramfunctionobject.h"
#include "account.h"
#include "auth.h"
#include "bots.h"
#include "channels.h"
#include "contacts.h"
#include "help.h"
#include "langpack.h"
#include "messages.h"
#include "payments.h"
#include "phone.h"
#include "photos.h"
#include "stickers.h"
#include "updates.h"
#include "upload.h"
#include "users.h"
