// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "cdnconfig.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

CdnConfig::CdnConfig(CdnConfigClassType classType, InboundPkt *in) :
    m_classType(classType)
{
    if(in) fetch(in);
}

CdnConfig::CdnConfig(InboundPkt *in) :
    m_classType(typeCdnConfig)
{
    fetch(in);
}

CdnConfig::CdnConfig(const CdnConfig &another) :
    TelegramTypeObject(),
    m_classType(typeCdnConfig)
{
    operator=(another);
}

CdnConfig::CdnConfig(const Null &null) :
    TelegramTypeObject(null),
    m_classType(typeCdnConfig)
{
}

CdnConfig::~CdnConfig() {
    
}

void CdnConfig::setPublicKeys(const QList<CdnPublicKey> &publicKeys) {
    m_publicKeys = publicKeys;
}

QList<CdnPublicKey> CdnConfig::publicKeys() const {
    return m_publicKeys;
}

bool CdnConfig::operator ==(const CdnConfig &b) const {
    return m_classType == b.m_classType &&
           m_publicKeys == b.m_publicKeys;
}

CdnConfig &CdnConfig::operator =(const CdnConfig &b) {
    m_classType = b.m_classType;
    m_publicKeys = b.m_publicKeys;
    setNull(b.isNull());
    return *this;
}

void CdnConfig::setClassType(CdnConfig::CdnConfigClassType classType) {
    m_classType = classType;
}

CdnConfig::CdnConfigClassType CdnConfig::classType() const {
    return m_classType;
}

bool CdnConfig::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeCdnConfig: {
        if(in->fetchInt() != (qint32)CoreTypes::typeVector) return false;
        qint32 m_publicKeys_length = in->fetchInt();
        m_publicKeys.clear();
        for (qint32 i = 0; i < m_publicKeys_length; i++) {
            CdnPublicKey type;
            type.fetch(in);
            m_publicKeys.append(type);
        }
        m_classType = static_cast<CdnConfigClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

bool CdnConfig::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeCdnConfig: {
        out->appendInt(CoreTypes::typeVector);
        out->appendInt(m_publicKeys.count());
        for (qint32 i = 0; i < m_publicKeys.count(); i++) {
            m_publicKeys[i].push(out);
        }
        return true;
    }
        break;
    
    default:
        return false;
    }
}

QMap<QString, QVariant> CdnConfig::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeCdnConfig: {
        result["classType"] = "CdnConfig::typeCdnConfig";
        QList<QVariant> _publicKeys;
        for(const CdnPublicKey &m__type: m_publicKeys)
            if( !m__type.isNull() ) _publicKeys << m__type.toMap();
        result["publicKeys"] = _publicKeys;
        return result;
    }
        break;
    
    default:
        return result;
    }
}

CdnConfig CdnConfig::fromMap(const QMap<QString, QVariant> &map) {
    CdnConfig result;
    if(map.value("classType").toString() == "CdnConfig::typeCdnConfig") {
        result.setClassType(typeCdnConfig);
        QList<QVariant> map_publicKeys = map["publicKeys"].toList();
        QList<CdnPublicKey> _publicKeys;
        for(const QVariant &var: map_publicKeys)
            _publicKeys << CdnPublicKey::fromMap(var.toMap());
        result.setPublicKeys(_publicKeys);
        return result;
    }
    return result;
}

CdnConfig CdnConfig::fromJson(const QString &json) {
    return CdnConfig::fromMap(QJsonDocument::fromJson(json.toUtf8()).toVariant().toMap());
}

QByteArray CdnConfig::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

QDataStream &operator<<(QDataStream &stream, const CdnConfig &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case CdnConfig::typeCdnConfig:
        stream << item.publicKeys();
        break;
    }
    return stream;
}

QDataStream &operator>>(QDataStream &stream, CdnConfig &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<CdnConfig::CdnConfigClassType>(type));
    switch(type) {
    case CdnConfig::typeCdnConfig: {
        QList<CdnPublicKey> m_public_keys;
        stream >> m_public_keys;
        item.setPublicKeys(m_public_keys);
    }
        break;
    }
    return stream;
}

QDebug operator<<(QDebug debug,  const CdnConfig &item) {
    QDebugStateSaver saver(debug);
    Q_UNUSED(saver)
    debug.nospace() << "Telegram.CdnConfig(";
    switch(item.classType()) {
    case CdnConfig::typeCdnConfig:
        debug.nospace() << "classType: typeCdnConfig";
        debug.nospace() << ", publicKeys: " << item.publicKeys();
        break;
    }
    debug.nospace() << ")";
    return debug;
}

