// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "helpinvitetext.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

HelpInviteText::HelpInviteText(HelpInviteTextClassType classType, InboundPkt *in) :
    m_classType(classType)
{
    if(in) fetch(in);
}

HelpInviteText::HelpInviteText(InboundPkt *in) :
    m_classType(typeHelpInviteText)
{
    fetch(in);
}

HelpInviteText::HelpInviteText(const HelpInviteText &another) :
    TelegramTypeObject(),
    m_classType(typeHelpInviteText)
{
    operator=(another);
}

HelpInviteText::HelpInviteText(const Null &null) :
    TelegramTypeObject(null),
    m_classType(typeHelpInviteText)
{
}

HelpInviteText::~HelpInviteText() {

}

void HelpInviteText::setMessage(const QString &message) {
    m_message = message;
}

QString HelpInviteText::message() const {
    return m_message;
}

bool HelpInviteText::operator ==(const HelpInviteText &b) const {
    return m_classType == b.m_classType &&
           m_message == b.m_message;
}

HelpInviteText &HelpInviteText::operator =(const HelpInviteText &b) {
    m_classType = b.m_classType;
    m_message = b.m_message;
    setNull(b.isNull());
    return *this;
}

void HelpInviteText::setClassType(HelpInviteText::HelpInviteTextClassType classType) {
    m_classType = classType;
}

HelpInviteText::HelpInviteTextClassType HelpInviteText::classType() const {
    return m_classType;
}

bool HelpInviteText::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeHelpInviteText: {
        m_message = in->fetchQString();
        m_classType = static_cast<HelpInviteTextClassType>(x);
        return true;
    }
        break;

    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

bool HelpInviteText::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeHelpInviteText: {
        out->appendQString(m_message);
        return true;
    }
        break;

    default:
        return false;
    }
}

QMap<QString, QVariant> HelpInviteText::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeHelpInviteText: {
        result["classType"] = "HelpInviteText::typeHelpInviteText";
        if( !m_message.isEmpty() ) result["message"] = QVariant::fromValue<QString>(m_message);
        return result;
    }
        break;

    default:
        return result;
    }
}

HelpInviteText HelpInviteText::fromMap(const QMap<QString, QVariant> &map) {
    HelpInviteText result;
    if(map.value("classType").toString() == "HelpInviteText::typeHelpInviteText") {
        result.setClassType(typeHelpInviteText);
        QVariant _message_var = map.value("message");
        if( !_message_var.isNull() ) {
            _message_var.convert( QVariant::nameToType("QString") );
            result.setMessage( _message_var.value<QString>() );
        }

        return result;
    }
    return result;
}

HelpInviteText HelpInviteText::fromJson(const QString &json) {
    return HelpInviteText::fromMap(QJsonDocument::fromJson(json.toUtf8()).toVariant().toMap());
}

QByteArray HelpInviteText::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

QDataStream &operator<<(QDataStream &stream, const HelpInviteText &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case HelpInviteText::typeHelpInviteText:
        stream << item.message();
        break;
    }
    return stream;
}

QDataStream &operator>>(QDataStream &stream, HelpInviteText &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<HelpInviteText::HelpInviteTextClassType>(type));
    switch(type) {
    case HelpInviteText::typeHelpInviteText: {
        QString m_message;
        stream >> m_message;
        item.setMessage(m_message);
    }
        break;
    }
    return stream;
}

/*QDebug operator<<(QDebug debug,  const HelpInviteText &item) {
    QDebugStateSaver saver(debug);
    Q_UNUSED(saver)
    debug.nospace() << "Telegram.HelpInviteText(";
    switch(item.classType()) {
    case HelpInviteText::typeHelpInviteText:
        debug.nospace() << "classType: typeHelpInviteText";
        debug.nospace() << ", message: " << item.message();
        break;
    }
    debug.nospace() << ")";
    return debug;
}
*/
