// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "inputfile.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

InputFile::InputFile(InputFileClassType classType, InboundPkt *in) :
    m_id(0),
    m_parts(0),
    m_classType(classType)
{
    if(in) fetch(in);
}

InputFile::InputFile(InboundPkt *in) :
    m_id(0),
    m_parts(0),
    m_classType(typeInputFile)
{
    fetch(in);
}

InputFile::InputFile(const InputFile &another) :
    TelegramTypeObject(),
    m_id(0),
    m_parts(0),
    m_classType(typeInputFile)
{
    operator=(another);
}

InputFile::InputFile(const Null &null) :
    TelegramTypeObject(null),
    m_id(0),
    m_parts(0),
    m_classType(typeInputFile)
{
}

InputFile::~InputFile() {
    
}

void InputFile::setId(qint64 id) {
    m_id = id;
}

qint64 InputFile::id() const {
    return m_id;
}

void InputFile::setMd5Checksum(const QString &md5Checksum) {
    m_md5Checksum = md5Checksum;
}

QString InputFile::md5Checksum() const {
    return m_md5Checksum;
}

void InputFile::setName(const QString &name) {
    m_name = name;
}

QString InputFile::name() const {
    return m_name;
}

void InputFile::setParts(qint32 parts) {
    m_parts = parts;
}

qint32 InputFile::parts() const {
    return m_parts;
}

bool InputFile::operator ==(const InputFile &b) const {
    return m_classType == b.m_classType &&
           m_id == b.m_id &&
           m_md5Checksum == b.m_md5Checksum &&
           m_name == b.m_name &&
           m_parts == b.m_parts;
}

InputFile &InputFile::operator =(const InputFile &b) {
    m_classType = b.m_classType;
    m_id = b.m_id;
    m_md5Checksum = b.m_md5Checksum;
    m_name = b.m_name;
    m_parts = b.m_parts;
    setNull(b.isNull());
    return *this;
}

void InputFile::setClassType(InputFile::InputFileClassType classType) {
    m_classType = classType;
}

InputFile::InputFileClassType InputFile::classType() const {
    return m_classType;
}

bool InputFile::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeInputFile: {
        m_id = in->fetchLong();
        m_parts = in->fetchInt();
        m_name = in->fetchQString();
        m_md5Checksum = in->fetchQString();
        m_classType = static_cast<InputFileClassType>(x);
        return true;
    }
        break;
    
    case typeInputFileBig: {
        m_id = in->fetchLong();
        m_parts = in->fetchInt();
        m_name = in->fetchQString();
        m_classType = static_cast<InputFileClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

bool InputFile::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeInputFile: {
        out->appendLong(m_id);
        out->appendInt(m_parts);
        out->appendQString(m_name);
        out->appendQString(m_md5Checksum);
        return true;
    }
        break;
    
    case typeInputFileBig: {
        out->appendLong(m_id);
        out->appendInt(m_parts);
        out->appendQString(m_name);
        return true;
    }
        break;
    
    default:
        return false;
    }
}

QMap<QString, QVariant> InputFile::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeInputFile: {
        result["classType"] = "InputFile::typeInputFile";
        if( id() ) result["id"] = QString::number(id());
        if( parts() ) result["parts"] = QString::number(parts());
        if( !m_name.isEmpty() ) result["name"] = QVariant::fromValue<QString>(m_name);
        if( !m_md5Checksum.isEmpty() ) result["md5Checksum"] = QVariant::fromValue<QString>(m_md5Checksum);
        return result;
    }
        break;
    
    case typeInputFileBig: {
        result["classType"] = "InputFile::typeInputFileBig";
        if( id() ) result["id"] = QString::number(id());
        if( parts() ) result["parts"] = QString::number(parts());
        if( !m_name.isEmpty() ) result["name"] = QVariant::fromValue<QString>(m_name);
        return result;
    }
        break;
    
    default:
        return result;
    }
}

InputFile InputFile::fromMap(const QMap<QString, QVariant> &map) {
    InputFile result;
    if(map.value("classType").toString() == "InputFile::typeInputFile") {
        result.setClassType(typeInputFile);
        QVariant _id_var = map.value("id");
        if( !_id_var.isNull() ) {
            _id_var.convert( QVariant::nameToType("qint64") );
            result.setId( _id_var.value<qint64>() );
        }
        
        QVariant _parts_var = map.value("parts");
        if( !_parts_var.isNull() ) {
            _parts_var.convert( QVariant::nameToType("qint32") );
            result.setParts( _parts_var.value<qint32>() );
        }
        
        QVariant _name_var = map.value("name");
        if( !_name_var.isNull() ) {
            _name_var.convert( QVariant::nameToType("QString") );
            result.setName( _name_var.value<QString>() );
        }
        
        QVariant _md5Checksum_var = map.value("md5Checksum");
        if( !_md5Checksum_var.isNull() ) {
            _md5Checksum_var.convert( QVariant::nameToType("QString") );
            result.setMd5Checksum( _md5Checksum_var.value<QString>() );
        }
        
        return result;
    }
    if(map.value("classType").toString() == "InputFile::typeInputFileBig") {
        result.setClassType(typeInputFileBig);
        QVariant _id_var = map.value("id");
        if( !_id_var.isNull() ) {
            _id_var.convert( QVariant::nameToType("qint64") );
            result.setId( _id_var.value<qint64>() );
        }
        
        QVariant _parts_var = map.value("parts");
        if( !_parts_var.isNull() ) {
            _parts_var.convert( QVariant::nameToType("qint32") );
            result.setParts( _parts_var.value<qint32>() );
        }
        
        QVariant _name_var = map.value("name");
        if( !_name_var.isNull() ) {
            _name_var.convert( QVariant::nameToType("QString") );
            result.setName( _name_var.value<QString>() );
        }
        
        return result;
    }
    return result;
}

InputFile InputFile::fromJson(const QString &json) {
    return InputFile::fromMap(QJsonDocument::fromJson(json.toUtf8()).toVariant().toMap());
}

QByteArray InputFile::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

QDataStream &operator<<(QDataStream &stream, const InputFile &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case InputFile::typeInputFile:
        stream << item.id();
        stream << item.parts();
        stream << item.name();
        stream << item.md5Checksum();
        break;
    case InputFile::typeInputFileBig:
        stream << item.id();
        stream << item.parts();
        stream << item.name();
        break;
    }
    return stream;
}

QDataStream &operator>>(QDataStream &stream, InputFile &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<InputFile::InputFileClassType>(type));
    switch(type) {
    case InputFile::typeInputFile: {
        qint64 m_id;
        stream >> m_id;
        item.setId(m_id);
        qint32 m_parts;
        stream >> m_parts;
        item.setParts(m_parts);
        QString m_name;
        stream >> m_name;
        item.setName(m_name);
        QString m_md5_checksum;
        stream >> m_md5_checksum;
        item.setMd5Checksum(m_md5_checksum);
    }
        break;
    case InputFile::typeInputFileBig: {
        qint64 m_id;
        stream >> m_id;
        item.setId(m_id);
        qint32 m_parts;
        stream >> m_parts;
        item.setParts(m_parts);
        QString m_name;
        stream >> m_name;
        item.setName(m_name);
    }
        break;
    }
    return stream;
}

QDebug operator<<(QDebug debug,  const InputFile &item) {
    QDebugStateSaver saver(debug);
    Q_UNUSED(saver)
    debug.nospace() << "Telegram.InputFile(";
    switch(item.classType()) {
    case InputFile::typeInputFile:
        debug.nospace() << "classType: typeInputFile";
        debug.nospace() << ", id: " << item.id();
        debug.nospace() << ", parts: " << item.parts();
        debug.nospace() << ", name: " << item.name();
        debug.nospace() << ", md5Checksum: " << item.md5Checksum();
        break;
    case InputFile::typeInputFileBig:
        debug.nospace() << "classType: typeInputFileBig";
        debug.nospace() << ", id: " << item.id();
        debug.nospace() << ", parts: " << item.parts();
        debug.nospace() << ", name: " << item.name();
        break;
    }
    debug.nospace() << ")";
    return debug;
}

