// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "inputphonecall.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

InputPhoneCall::InputPhoneCall(InputPhoneCallClassType classType, InboundPkt *in) :
    m_accessHash(0),
    m_id(0),
    m_classType(classType)
{
    if(in) fetch(in);
}

InputPhoneCall::InputPhoneCall(InboundPkt *in) :
    m_accessHash(0),
    m_id(0),
    m_classType(typeInputPhoneCall)
{
    fetch(in);
}

InputPhoneCall::InputPhoneCall(const InputPhoneCall &another) :
    TelegramTypeObject(),
    m_accessHash(0),
    m_id(0),
    m_classType(typeInputPhoneCall)
{
    operator=(another);
}

InputPhoneCall::InputPhoneCall(const Null &null) :
    TelegramTypeObject(null),
    m_accessHash(0),
    m_id(0),
    m_classType(typeInputPhoneCall)
{
}

InputPhoneCall::~InputPhoneCall() {
    
}

void InputPhoneCall::setAccessHash(qint64 accessHash) {
    m_accessHash = accessHash;
}

qint64 InputPhoneCall::accessHash() const {
    return m_accessHash;
}

void InputPhoneCall::setId(qint64 id) {
    m_id = id;
}

qint64 InputPhoneCall::id() const {
    return m_id;
}

bool InputPhoneCall::operator ==(const InputPhoneCall &b) const {
    return m_classType == b.m_classType &&
           m_accessHash == b.m_accessHash &&
           m_id == b.m_id;
}

InputPhoneCall &InputPhoneCall::operator =(const InputPhoneCall &b) {
    m_classType = b.m_classType;
    m_accessHash = b.m_accessHash;
    m_id = b.m_id;
    setNull(b.isNull());
    return *this;
}

void InputPhoneCall::setClassType(InputPhoneCall::InputPhoneCallClassType classType) {
    m_classType = classType;
}

InputPhoneCall::InputPhoneCallClassType InputPhoneCall::classType() const {
    return m_classType;
}

bool InputPhoneCall::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeInputPhoneCall: {
        m_id = in->fetchLong();
        m_accessHash = in->fetchLong();
        m_classType = static_cast<InputPhoneCallClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

bool InputPhoneCall::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeInputPhoneCall: {
        out->appendLong(m_id);
        out->appendLong(m_accessHash);
        return true;
    }
        break;
    
    default:
        return false;
    }
}

QMap<QString, QVariant> InputPhoneCall::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeInputPhoneCall: {
        result["classType"] = "InputPhoneCall::typeInputPhoneCall";
        if( id() ) result["id"] = QString::number(id());
        if( accessHash() ) result["accessHash"] = QString::number(accessHash());
        return result;
    }
        break;
    
    default:
        return result;
    }
}

InputPhoneCall InputPhoneCall::fromMap(const QMap<QString, QVariant> &map) {
    InputPhoneCall result;
    if(map.value("classType").toString() == "InputPhoneCall::typeInputPhoneCall") {
        result.setClassType(typeInputPhoneCall);
        QVariant _id_var = map.value("id");
        if( !_id_var.isNull() ) {
            _id_var.convert( QVariant::nameToType("qint64") );
            result.setId( _id_var.value<qint64>() );
        }
        
        QVariant _accessHash_var = map.value("accessHash");
        if( !_accessHash_var.isNull() ) {
            _accessHash_var.convert( QVariant::nameToType("qint64") );
            result.setAccessHash( _accessHash_var.value<qint64>() );
        }
        
        return result;
    }
    return result;
}

InputPhoneCall InputPhoneCall::fromJson(const QString &json) {
    return InputPhoneCall::fromMap(QJsonDocument::fromJson(json.toUtf8()).toVariant().toMap());
}

QByteArray InputPhoneCall::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

QDataStream &operator<<(QDataStream &stream, const InputPhoneCall &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case InputPhoneCall::typeInputPhoneCall:
        stream << item.id();
        stream << item.accessHash();
        break;
    }
    return stream;
}

QDataStream &operator>>(QDataStream &stream, InputPhoneCall &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<InputPhoneCall::InputPhoneCallClassType>(type));
    switch(type) {
    case InputPhoneCall::typeInputPhoneCall: {
        qint64 m_id;
        stream >> m_id;
        item.setId(m_id);
        qint64 m_access_hash;
        stream >> m_access_hash;
        item.setAccessHash(m_access_hash);
    }
        break;
    }
    return stream;
}

QDebug operator<<(QDebug debug,  const InputPhoneCall &item) {
    QDebugStateSaver saver(debug);
    Q_UNUSED(saver)
    debug.nospace() << "Telegram.InputPhoneCall(";
    switch(item.classType()) {
    case InputPhoneCall::typeInputPhoneCall:
        debug.nospace() << "classType: typeInputPhoneCall";
        debug.nospace() << ", id: " << item.id();
        debug.nospace() << ", accessHash: " << item.accessHash();
        break;
    }
    debug.nospace() << ")";
    return debug;
}

