// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_MASKCOORDS
#define LQTG_TYPE_MASKCOORDS

#include "telegramtypeobject.h"

#include <QMetaType>
#include <QVariant>
#include "../coretypes.h"

#include <QDataStream>

#include <QtGlobal>

class LIBQTELEGRAMSHARED_EXPORT MaskCoords : public TelegramTypeObject
{
public:
    enum MaskCoordsClassType {
        typeMaskCoords = 0xaed6dbb2
    };

    MaskCoords(MaskCoordsClassType classType = typeMaskCoords, InboundPkt *in = 0);
    MaskCoords(InboundPkt *in);
    MaskCoords(const Null&);
    MaskCoords(const MaskCoords &another);
    virtual ~MaskCoords();

    void setN(qint32 n);
    qint32 n() const;

    void setX(qreal x);
    qreal x() const;

    void setY(qreal y);
    qreal y() const;

    void setZoom(qreal zoom);
    qreal zoom() const;

    void setClassType(MaskCoordsClassType classType);
    MaskCoordsClassType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    QMap<QString, QVariant> toMap() const;
    static MaskCoords fromMap(const QMap<QString, QVariant> &map);
    static MaskCoords fromJson(const QString &json);

    bool operator ==(const MaskCoords &b) const;
    MaskCoords &operator =(const MaskCoords &b);

    bool operator==(bool stt) const { return isNull() != stt; }
    bool operator!=(bool stt) const { return !operator ==(stt); }

    QByteArray getHash(QCryptographicHash::Algorithm alg = QCryptographicHash::Md5) const;

private:
    qint32 m_n;
    qreal m_x;
    qreal m_y;
    qreal m_zoom;
    MaskCoordsClassType m_classType;
};

Q_DECLARE_METATYPE(MaskCoords)

QDataStream LIBQTELEGRAMSHARED_EXPORT &operator<<(QDataStream &stream, const MaskCoords &item);
QDataStream LIBQTELEGRAMSHARED_EXPORT &operator>>(QDataStream &stream, MaskCoords &item);

QDebug LIBQTELEGRAMSHARED_EXPORT operator<<(QDebug debug,  const MaskCoords &item);

#endif // LQTG_TYPE_MASKCOORDS
