// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "messagesaffectedhistory.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

MessagesAffectedHistory::MessagesAffectedHistory(MessagesAffectedHistoryClassType classType, InboundPkt *in) :
    m_offset(0),
    m_pts(0),
    m_ptsCount(0),
    m_classType(classType)
{
    if(in) fetch(in);
}

MessagesAffectedHistory::MessagesAffectedHistory(InboundPkt *in) :
    m_offset(0),
    m_pts(0),
    m_ptsCount(0),
    m_classType(typeMessagesAffectedHistory)
{
    fetch(in);
}

MessagesAffectedHistory::MessagesAffectedHistory(const MessagesAffectedHistory &another) :
    TelegramTypeObject(),
    m_offset(0),
    m_pts(0),
    m_ptsCount(0),
    m_classType(typeMessagesAffectedHistory)
{
    operator=(another);
}

MessagesAffectedHistory::MessagesAffectedHistory(const Null &null) :
    TelegramTypeObject(null),
    m_offset(0),
    m_pts(0),
    m_ptsCount(0),
    m_classType(typeMessagesAffectedHistory)
{
}

MessagesAffectedHistory::~MessagesAffectedHistory() {
    
}

void MessagesAffectedHistory::setOffset(qint32 offset) {
    m_offset = offset;
}

qint32 MessagesAffectedHistory::offset() const {
    return m_offset;
}

void MessagesAffectedHistory::setPts(qint32 pts) {
    m_pts = pts;
}

qint32 MessagesAffectedHistory::pts() const {
    return m_pts;
}

void MessagesAffectedHistory::setPtsCount(qint32 ptsCount) {
    m_ptsCount = ptsCount;
}

qint32 MessagesAffectedHistory::ptsCount() const {
    return m_ptsCount;
}

bool MessagesAffectedHistory::operator ==(const MessagesAffectedHistory &b) const {
    return m_classType == b.m_classType &&
           m_offset == b.m_offset &&
           m_pts == b.m_pts &&
           m_ptsCount == b.m_ptsCount;
}

MessagesAffectedHistory &MessagesAffectedHistory::operator =(const MessagesAffectedHistory &b) {
    m_classType = b.m_classType;
    m_offset = b.m_offset;
    m_pts = b.m_pts;
    m_ptsCount = b.m_ptsCount;
    setNull(b.isNull());
    return *this;
}

void MessagesAffectedHistory::setClassType(MessagesAffectedHistory::MessagesAffectedHistoryClassType classType) {
    m_classType = classType;
}

MessagesAffectedHistory::MessagesAffectedHistoryClassType MessagesAffectedHistory::classType() const {
    return m_classType;
}

bool MessagesAffectedHistory::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeMessagesAffectedHistory: {
        m_pts = in->fetchInt();
        m_ptsCount = in->fetchInt();
        m_offset = in->fetchInt();
        m_classType = static_cast<MessagesAffectedHistoryClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

bool MessagesAffectedHistory::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeMessagesAffectedHistory: {
        out->appendInt(m_pts);
        out->appendInt(m_ptsCount);
        out->appendInt(m_offset);
        return true;
    }
        break;
    
    default:
        return false;
    }
}

QMap<QString, QVariant> MessagesAffectedHistory::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeMessagesAffectedHistory: {
        result["classType"] = "MessagesAffectedHistory::typeMessagesAffectedHistory";
        if( pts() ) result["pts"] = QString::number(pts());
        if( ptsCount() ) result["ptsCount"] = QString::number(ptsCount());
        if( offset() ) result["offset"] = QString::number(offset());
        return result;
    }
        break;
    
    default:
        return result;
    }
}

MessagesAffectedHistory MessagesAffectedHistory::fromMap(const QMap<QString, QVariant> &map) {
    MessagesAffectedHistory result;
    if(map.value("classType").toString() == "MessagesAffectedHistory::typeMessagesAffectedHistory") {
        result.setClassType(typeMessagesAffectedHistory);
        QVariant _pts_var = map.value("pts");
        if( !_pts_var.isNull() ) {
            _pts_var.convert( QVariant::nameToType("qint32") );
            result.setPts( _pts_var.value<qint32>() );
        }
        
        QVariant _ptsCount_var = map.value("ptsCount");
        if( !_ptsCount_var.isNull() ) {
            _ptsCount_var.convert( QVariant::nameToType("qint32") );
            result.setPtsCount( _ptsCount_var.value<qint32>() );
        }
        
        QVariant _offset_var = map.value("offset");
        if( !_offset_var.isNull() ) {
            _offset_var.convert( QVariant::nameToType("qint32") );
            result.setOffset( _offset_var.value<qint32>() );
        }
        
        return result;
    }
    return result;
}

MessagesAffectedHistory MessagesAffectedHistory::fromJson(const QString &json) {
    return MessagesAffectedHistory::fromMap(QJsonDocument::fromJson(json.toUtf8()).toVariant().toMap());
}

QByteArray MessagesAffectedHistory::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

QDataStream &operator<<(QDataStream &stream, const MessagesAffectedHistory &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case MessagesAffectedHistory::typeMessagesAffectedHistory:
        stream << item.pts();
        stream << item.ptsCount();
        stream << item.offset();
        break;
    }
    return stream;
}

QDataStream &operator>>(QDataStream &stream, MessagesAffectedHistory &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<MessagesAffectedHistory::MessagesAffectedHistoryClassType>(type));
    switch(type) {
    case MessagesAffectedHistory::typeMessagesAffectedHistory: {
        qint32 m_pts;
        stream >> m_pts;
        item.setPts(m_pts);
        qint32 m_pts_count;
        stream >> m_pts_count;
        item.setPtsCount(m_pts_count);
        qint32 m_offset;
        stream >> m_offset;
        item.setOffset(m_offset);
    }
        break;
    }
    return stream;
}

QDebug operator<<(QDebug debug,  const MessagesAffectedHistory &item) {
    QDebugStateSaver saver(debug);
    Q_UNUSED(saver)
    debug.nospace() << "Telegram.MessagesAffectedHistory(";
    switch(item.classType()) {
    case MessagesAffectedHistory::typeMessagesAffectedHistory:
        debug.nospace() << "classType: typeMessagesAffectedHistory";
        debug.nospace() << ", pts: " << item.pts();
        debug.nospace() << ", ptsCount: " << item.ptsCount();
        debug.nospace() << ", offset: " << item.offset();
        break;
    }
    debug.nospace() << ")";
    return debug;
}

