// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "sendmessageaction.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

SendMessageAction::SendMessageAction(SendMessageActionClassType classType, InboundPkt *in) :
    m_progress(0),
    m_classType(classType)
{
    if(in) fetch(in);
}

SendMessageAction::SendMessageAction(InboundPkt *in) :
    m_progress(0),
    m_classType(typeSendMessageTypingAction)
{
    fetch(in);
}

SendMessageAction::SendMessageAction(const SendMessageAction &another) :
    TelegramTypeObject(),
    m_progress(0),
    m_classType(typeSendMessageTypingAction)
{
    operator=(another);
}

SendMessageAction::SendMessageAction(const Null &null) :
    TelegramTypeObject(null),
    m_progress(0),
    m_classType(typeSendMessageTypingAction)
{
}

SendMessageAction::~SendMessageAction() {
    
}

void SendMessageAction::setProgress(qint32 progress) {
    m_progress = progress;
}

qint32 SendMessageAction::progress() const {
    return m_progress;
}

bool SendMessageAction::operator ==(const SendMessageAction &b) const {
    return m_classType == b.m_classType &&
           m_progress == b.m_progress;
}

SendMessageAction &SendMessageAction::operator =(const SendMessageAction &b) {
    m_classType = b.m_classType;
    m_progress = b.m_progress;
    setNull(b.isNull());
    return *this;
}

void SendMessageAction::setClassType(SendMessageAction::SendMessageActionClassType classType) {
    m_classType = classType;
}

SendMessageAction::SendMessageActionClassType SendMessageAction::classType() const {
    return m_classType;
}

bool SendMessageAction::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeSendMessageTypingAction: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageCancelAction: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageRecordVideoAction: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageUploadVideoAction: {
        m_progress = in->fetchInt();
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageRecordAudioAction: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageUploadAudioAction: {
        m_progress = in->fetchInt();
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageUploadPhotoAction: {
        m_progress = in->fetchInt();
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageUploadDocumentAction: {
        m_progress = in->fetchInt();
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageGeoLocationAction: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageChooseContactAction: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageGamePlayAction: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageRecordRoundAction: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageUploadRoundAction: {
        m_progress = in->fetchInt();
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageUploadVideoActionSecret17: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageUploadAudioActionSecret17: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageUploadPhotoActionSecret17: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    case typeSendMessageUploadDocumentActionSecret17: {
        m_classType = static_cast<SendMessageActionClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

bool SendMessageAction::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeSendMessageTypingAction: {
        return true;
    }
        break;
    
    case typeSendMessageCancelAction: {
        return true;
    }
        break;
    
    case typeSendMessageRecordVideoAction: {
        return true;
    }
        break;
    
    case typeSendMessageUploadVideoAction: {
        out->appendInt(m_progress);
        return true;
    }
        break;
    
    case typeSendMessageRecordAudioAction: {
        return true;
    }
        break;
    
    case typeSendMessageUploadAudioAction: {
        out->appendInt(m_progress);
        return true;
    }
        break;
    
    case typeSendMessageUploadPhotoAction: {
        out->appendInt(m_progress);
        return true;
    }
        break;
    
    case typeSendMessageUploadDocumentAction: {
        out->appendInt(m_progress);
        return true;
    }
        break;
    
    case typeSendMessageGeoLocationAction: {
        return true;
    }
        break;
    
    case typeSendMessageChooseContactAction: {
        return true;
    }
        break;
    
    case typeSendMessageGamePlayAction: {
        return true;
    }
        break;
    
    case typeSendMessageRecordRoundAction: {
        return true;
    }
        break;
    
    case typeSendMessageUploadRoundAction: {
        out->appendInt(m_progress);
        return true;
    }
        break;
    
    case typeSendMessageUploadVideoActionSecret17: {
        return true;
    }
        break;
    
    case typeSendMessageUploadAudioActionSecret17: {
        return true;
    }
        break;
    
    case typeSendMessageUploadPhotoActionSecret17: {
        return true;
    }
        break;
    
    case typeSendMessageUploadDocumentActionSecret17: {
        return true;
    }
        break;
    
    default:
        return false;
    }
}

QMap<QString, QVariant> SendMessageAction::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeSendMessageTypingAction: {
        result["classType"] = "SendMessageAction::typeSendMessageTypingAction";
        return result;
    }
        break;
    
    case typeSendMessageCancelAction: {
        result["classType"] = "SendMessageAction::typeSendMessageCancelAction";
        return result;
    }
        break;
    
    case typeSendMessageRecordVideoAction: {
        result["classType"] = "SendMessageAction::typeSendMessageRecordVideoAction";
        return result;
    }
        break;
    
    case typeSendMessageUploadVideoAction: {
        result["classType"] = "SendMessageAction::typeSendMessageUploadVideoAction";
        if( progress() ) result["progress"] = QString::number(progress());
        return result;
    }
        break;
    
    case typeSendMessageRecordAudioAction: {
        result["classType"] = "SendMessageAction::typeSendMessageRecordAudioAction";
        return result;
    }
        break;
    
    case typeSendMessageUploadAudioAction: {
        result["classType"] = "SendMessageAction::typeSendMessageUploadAudioAction";
        if( progress() ) result["progress"] = QString::number(progress());
        return result;
    }
        break;
    
    case typeSendMessageUploadPhotoAction: {
        result["classType"] = "SendMessageAction::typeSendMessageUploadPhotoAction";
        if( progress() ) result["progress"] = QString::number(progress());
        return result;
    }
        break;
    
    case typeSendMessageUploadDocumentAction: {
        result["classType"] = "SendMessageAction::typeSendMessageUploadDocumentAction";
        if( progress() ) result["progress"] = QString::number(progress());
        return result;
    }
        break;
    
    case typeSendMessageGeoLocationAction: {
        result["classType"] = "SendMessageAction::typeSendMessageGeoLocationAction";
        return result;
    }
        break;
    
    case typeSendMessageChooseContactAction: {
        result["classType"] = "SendMessageAction::typeSendMessageChooseContactAction";
        return result;
    }
        break;
    
    case typeSendMessageGamePlayAction: {
        result["classType"] = "SendMessageAction::typeSendMessageGamePlayAction";
        return result;
    }
        break;
    
    case typeSendMessageRecordRoundAction: {
        result["classType"] = "SendMessageAction::typeSendMessageRecordRoundAction";
        return result;
    }
        break;
    
    case typeSendMessageUploadRoundAction: {
        result["classType"] = "SendMessageAction::typeSendMessageUploadRoundAction";
        if( progress() ) result["progress"] = QString::number(progress());
        return result;
    }
        break;
    
    case typeSendMessageUploadVideoActionSecret17: {
        result["classType"] = "SendMessageAction::typeSendMessageUploadVideoActionSecret17";
        return result;
    }
        break;
    
    case typeSendMessageUploadAudioActionSecret17: {
        result["classType"] = "SendMessageAction::typeSendMessageUploadAudioActionSecret17";
        return result;
    }
        break;
    
    case typeSendMessageUploadPhotoActionSecret17: {
        result["classType"] = "SendMessageAction::typeSendMessageUploadPhotoActionSecret17";
        return result;
    }
        break;
    
    case typeSendMessageUploadDocumentActionSecret17: {
        result["classType"] = "SendMessageAction::typeSendMessageUploadDocumentActionSecret17";
        return result;
    }
        break;
    
    default:
        return result;
    }
}

SendMessageAction SendMessageAction::fromMap(const QMap<QString, QVariant> &map) {
    SendMessageAction result;
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageTypingAction") {
        result.setClassType(typeSendMessageTypingAction);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageCancelAction") {
        result.setClassType(typeSendMessageCancelAction);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageRecordVideoAction") {
        result.setClassType(typeSendMessageRecordVideoAction);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageUploadVideoAction") {
        result.setClassType(typeSendMessageUploadVideoAction);
        QVariant _progress_var = map.value("progress");
        if( !_progress_var.isNull() ) {
            _progress_var.convert( QVariant::nameToType("qint32") );
            result.setProgress( _progress_var.value<qint32>() );
        }
        
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageRecordAudioAction") {
        result.setClassType(typeSendMessageRecordAudioAction);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageUploadAudioAction") {
        result.setClassType(typeSendMessageUploadAudioAction);
        QVariant _progress_var = map.value("progress");
        if( !_progress_var.isNull() ) {
            _progress_var.convert( QVariant::nameToType("qint32") );
            result.setProgress( _progress_var.value<qint32>() );
        }
        
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageUploadPhotoAction") {
        result.setClassType(typeSendMessageUploadPhotoAction);
        QVariant _progress_var = map.value("progress");
        if( !_progress_var.isNull() ) {
            _progress_var.convert( QVariant::nameToType("qint32") );
            result.setProgress( _progress_var.value<qint32>() );
        }
        
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageUploadDocumentAction") {
        result.setClassType(typeSendMessageUploadDocumentAction);
        QVariant _progress_var = map.value("progress");
        if( !_progress_var.isNull() ) {
            _progress_var.convert( QVariant::nameToType("qint32") );
            result.setProgress( _progress_var.value<qint32>() );
        }
        
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageGeoLocationAction") {
        result.setClassType(typeSendMessageGeoLocationAction);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageChooseContactAction") {
        result.setClassType(typeSendMessageChooseContactAction);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageGamePlayAction") {
        result.setClassType(typeSendMessageGamePlayAction);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageRecordRoundAction") {
        result.setClassType(typeSendMessageRecordRoundAction);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageUploadRoundAction") {
        result.setClassType(typeSendMessageUploadRoundAction);
        QVariant _progress_var = map.value("progress");
        if( !_progress_var.isNull() ) {
            _progress_var.convert( QVariant::nameToType("qint32") );
            result.setProgress( _progress_var.value<qint32>() );
        }
        
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageTypingActionSecret17") {
        result.setClassType(typeSendMessageTypingActionSecret17);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageCancelActionSecret17") {
        result.setClassType(typeSendMessageCancelActionSecret17);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageRecordVideoActionSecret17") {
        result.setClassType(typeSendMessageRecordVideoActionSecret17);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageUploadVideoActionSecret17") {
        result.setClassType(typeSendMessageUploadVideoActionSecret17);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageRecordAudioActionSecret17") {
        result.setClassType(typeSendMessageRecordAudioActionSecret17);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageUploadAudioActionSecret17") {
        result.setClassType(typeSendMessageUploadAudioActionSecret17);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageUploadPhotoActionSecret17") {
        result.setClassType(typeSendMessageUploadPhotoActionSecret17);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageUploadDocumentActionSecret17") {
        result.setClassType(typeSendMessageUploadDocumentActionSecret17);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageGeoLocationActionSecret17") {
        result.setClassType(typeSendMessageGeoLocationActionSecret17);
        return result;
    }
    if(map.value("classType").toString() == "SendMessageAction::typeSendMessageChooseContactActionSecret17") {
        result.setClassType(typeSendMessageChooseContactActionSecret17);
        return result;
    }
    return result;
}

SendMessageAction SendMessageAction::fromJson(const QString &json) {
    return SendMessageAction::fromMap(QJsonDocument::fromJson(json.toUtf8()).toVariant().toMap());
}

QByteArray SendMessageAction::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

QDataStream &operator<<(QDataStream &stream, const SendMessageAction &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case SendMessageAction::typeSendMessageTypingAction:
        
        break;
    case SendMessageAction::typeSendMessageCancelAction:
        
        break;
    case SendMessageAction::typeSendMessageRecordVideoAction:
        
        break;
    case SendMessageAction::typeSendMessageUploadVideoAction:
        stream << item.progress();
        break;
    case SendMessageAction::typeSendMessageRecordAudioAction:
        
        break;
    case SendMessageAction::typeSendMessageUploadAudioAction:
        stream << item.progress();
        break;
    case SendMessageAction::typeSendMessageUploadPhotoAction:
        stream << item.progress();
        break;
    case SendMessageAction::typeSendMessageUploadDocumentAction:
        stream << item.progress();
        break;
    case SendMessageAction::typeSendMessageGeoLocationAction:
        
        break;
    case SendMessageAction::typeSendMessageChooseContactAction:
        
        break;
    case SendMessageAction::typeSendMessageGamePlayAction:
        
        break;
    case SendMessageAction::typeSendMessageRecordRoundAction:
        
        break;
    case SendMessageAction::typeSendMessageUploadRoundAction:
        stream << item.progress();
        break;
    case SendMessageAction::typeSendMessageUploadVideoActionSecret17:
        
        break;
    case SendMessageAction::typeSendMessageUploadAudioActionSecret17:
        
        break;
    case SendMessageAction::typeSendMessageUploadPhotoActionSecret17:
        
        break;
    case SendMessageAction::typeSendMessageUploadDocumentActionSecret17:
        
        break;
    }
    return stream;
}

QDataStream &operator>>(QDataStream &stream, SendMessageAction &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<SendMessageAction::SendMessageActionClassType>(type));
    switch(type) {
    case SendMessageAction::typeSendMessageTypingAction: {
        
    }
        break;
    case SendMessageAction::typeSendMessageCancelAction: {
        
    }
        break;
    case SendMessageAction::typeSendMessageRecordVideoAction: {
        
    }
        break;
    case SendMessageAction::typeSendMessageUploadVideoAction: {
        qint32 m_progress;
        stream >> m_progress;
        item.setProgress(m_progress);
    }
        break;
    case SendMessageAction::typeSendMessageRecordAudioAction: {
        
    }
        break;
    case SendMessageAction::typeSendMessageUploadAudioAction: {
        qint32 m_progress;
        stream >> m_progress;
        item.setProgress(m_progress);
    }
        break;
    case SendMessageAction::typeSendMessageUploadPhotoAction: {
        qint32 m_progress;
        stream >> m_progress;
        item.setProgress(m_progress);
    }
        break;
    case SendMessageAction::typeSendMessageUploadDocumentAction: {
        qint32 m_progress;
        stream >> m_progress;
        item.setProgress(m_progress);
    }
        break;
    case SendMessageAction::typeSendMessageGeoLocationAction: {
        
    }
        break;
    case SendMessageAction::typeSendMessageChooseContactAction: {
        
    }
        break;
    case SendMessageAction::typeSendMessageGamePlayAction: {
        
    }
        break;
    case SendMessageAction::typeSendMessageRecordRoundAction: {
        
    }
        break;
    case SendMessageAction::typeSendMessageUploadRoundAction: {
        qint32 m_progress;
        stream >> m_progress;
        item.setProgress(m_progress);
    }
        break;
    case SendMessageAction::typeSendMessageUploadVideoActionSecret17: {
        
    }
        break;
    case SendMessageAction::typeSendMessageUploadAudioActionSecret17: {
        
    }
        break;
    case SendMessageAction::typeSendMessageUploadPhotoActionSecret17: {
        
    }
        break;
    case SendMessageAction::typeSendMessageUploadDocumentActionSecret17: {
        
    }
        break;
    }
    return stream;
}

QDebug operator<<(QDebug debug,  const SendMessageAction &item) {
    QDebugStateSaver saver(debug);
    Q_UNUSED(saver)
    debug.nospace() << "Telegram.SendMessageAction(";
    switch(item.classType()) {
    case SendMessageAction::typeSendMessageTypingAction:
        debug.nospace() << "classType: typeSendMessageTypingAction";
        break;
    case SendMessageAction::typeSendMessageCancelAction:
        debug.nospace() << "classType: typeSendMessageCancelAction";
        break;
    case SendMessageAction::typeSendMessageRecordVideoAction:
        debug.nospace() << "classType: typeSendMessageRecordVideoAction";
        break;
    case SendMessageAction::typeSendMessageUploadVideoAction:
        debug.nospace() << "classType: typeSendMessageUploadVideoAction";
        debug.nospace() << ", progress: " << item.progress();
        break;
    case SendMessageAction::typeSendMessageRecordAudioAction:
        debug.nospace() << "classType: typeSendMessageRecordAudioAction";
        break;
    case SendMessageAction::typeSendMessageUploadAudioAction:
        debug.nospace() << "classType: typeSendMessageUploadAudioAction";
        debug.nospace() << ", progress: " << item.progress();
        break;
    case SendMessageAction::typeSendMessageUploadPhotoAction:
        debug.nospace() << "classType: typeSendMessageUploadPhotoAction";
        debug.nospace() << ", progress: " << item.progress();
        break;
    case SendMessageAction::typeSendMessageUploadDocumentAction:
        debug.nospace() << "classType: typeSendMessageUploadDocumentAction";
        debug.nospace() << ", progress: " << item.progress();
        break;
    case SendMessageAction::typeSendMessageGeoLocationAction:
        debug.nospace() << "classType: typeSendMessageGeoLocationAction";
        break;
    case SendMessageAction::typeSendMessageChooseContactAction:
        debug.nospace() << "classType: typeSendMessageChooseContactAction";
        break;
    case SendMessageAction::typeSendMessageGamePlayAction:
        debug.nospace() << "classType: typeSendMessageGamePlayAction";
        break;
    case SendMessageAction::typeSendMessageRecordRoundAction:
        debug.nospace() << "classType: typeSendMessageRecordRoundAction";
        break;
    case SendMessageAction::typeSendMessageUploadRoundAction:
        debug.nospace() << "classType: typeSendMessageUploadRoundAction";
        debug.nospace() << ", progress: " << item.progress();
        break;
    case SendMessageAction::typeSendMessageUploadVideoActionSecret17:
        debug.nospace() << "classType: typeSendMessageUploadVideoActionSecret17";
        break;
    case SendMessageAction::typeSendMessageUploadAudioActionSecret17:
        debug.nospace() << "classType: typeSendMessageUploadAudioActionSecret17";
        break;
    case SendMessageAction::typeSendMessageUploadPhotoActionSecret17:
        debug.nospace() << "classType: typeSendMessageUploadPhotoActionSecret17";
        break;
    case SendMessageAction::typeSendMessageUploadDocumentActionSecret17:
        debug.nospace() << "classType: typeSendMessageUploadDocumentActionSecret17";
        break;
    }
    debug.nospace() << ")";
    return debug;
}

