// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_INPUTWEBDOCUMENT_OBJECT
#define LQTG_TYPE_INPUTWEBDOCUMENT_OBJECT

#include "telegramtypeqobject.h"
#include "telegram/types/inputwebdocument.h"

#include <QPointer>

class LIBQTELEGRAMSHARED_EXPORT InputWebDocumentObject : public TelegramTypeQObject
{
    Q_OBJECT
    Q_ENUMS(InputWebDocumentClassType)
    Q_PROPERTY(QList<DocumentAttribute> attributes READ attributes WRITE setAttributes NOTIFY attributesChanged)
    Q_PROPERTY(QString mimeType READ mimeType WRITE setMimeType NOTIFY mimeTypeChanged)
    Q_PROPERTY(qint32 size READ size WRITE setSize NOTIFY sizeChanged)
    Q_PROPERTY(QString url READ url WRITE setUrl NOTIFY urlChanged)
    Q_PROPERTY(InputWebDocument core READ core WRITE setCore NOTIFY coreChanged)
    Q_PROPERTY(quint32 classType READ classType WRITE setClassType NOTIFY classTypeChanged)

public:
    enum InputWebDocumentClassType {
        TypeInputWebDocument
    };

    InputWebDocumentObject(const InputWebDocument &core, QObject *parent = 0);
    InputWebDocumentObject(QObject *parent = 0);
    virtual ~InputWebDocumentObject();

    void setAttributes(const QList<DocumentAttribute> &attributes);
    QList<DocumentAttribute> attributes() const;

    void setMimeType(const QString &mimeType);
    QString mimeType() const;

    void setSize(qint32 size);
    qint32 size() const;

    void setUrl(const QString &url);
    QString url() const;

    void setClassType(quint32 classType);
    quint32 classType() const;

    void setCore(const InputWebDocument &core);
    InputWebDocument core() const;

    InputWebDocumentObject &operator =(const InputWebDocument &b);
    bool operator ==(const InputWebDocument &b) const;

Q_SIGNALS:
    void coreChanged();
    void classTypeChanged();
    void attributesChanged();
    void mimeTypeChanged();
    void sizeChanged();
    void urlChanged();

private Q_SLOTS:

private:
    InputWebDocument m_core;
};

#endif // LQTG_TYPE_INPUTWEBDOCUMENT_OBJECT
