// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_KEYBOARDBUTTON_OBJECT
#define LQTG_TYPE_KEYBOARDBUTTON_OBJECT

#include "telegramtypeqobject.h"
#include "telegram/types/keyboardbutton.h"

#include <QPointer>

class LIBQTELEGRAMSHARED_EXPORT KeyboardButtonObject : public TelegramTypeQObject
{
    Q_OBJECT
    Q_ENUMS(KeyboardButtonClassType)
    Q_PROPERTY(QByteArray data READ data WRITE setData NOTIFY dataChanged)
    Q_PROPERTY(qint32 flags READ flags WRITE setFlags NOTIFY flagsChanged)
    Q_PROPERTY(QString query READ query WRITE setQuery NOTIFY queryChanged)
    Q_PROPERTY(bool samePeer READ samePeer WRITE setSamePeer NOTIFY samePeerChanged)
    Q_PROPERTY(QString text READ text WRITE setText NOTIFY textChanged)
    Q_PROPERTY(QString url READ url WRITE setUrl NOTIFY urlChanged)
    Q_PROPERTY(KeyboardButton core READ core WRITE setCore NOTIFY coreChanged)
    Q_PROPERTY(quint32 classType READ classType WRITE setClassType NOTIFY classTypeChanged)

public:
    enum KeyboardButtonClassType {
        TypeKeyboardButton,
        TypeKeyboardButtonUrl,
        TypeKeyboardButtonCallback,
        TypeKeyboardButtonRequestPhone,
        TypeKeyboardButtonRequestGeoLocation,
        TypeKeyboardButtonSwitchInline,
        TypeKeyboardButtonGame,
        TypeKeyboardButtonBuy
    };

    KeyboardButtonObject(const KeyboardButton &core, QObject *parent = 0);
    KeyboardButtonObject(QObject *parent = 0);
    virtual ~KeyboardButtonObject();

    void setData(const QByteArray &data);
    QByteArray data() const;

    void setFlags(qint32 flags);
    qint32 flags() const;

    void setQuery(const QString &query);
    QString query() const;

    void setSamePeer(bool samePeer);
    bool samePeer() const;

    void setText(const QString &text);
    QString text() const;

    void setUrl(const QString &url);
    QString url() const;

    void setClassType(quint32 classType);
    quint32 classType() const;

    void setCore(const KeyboardButton &core);
    KeyboardButton core() const;

    KeyboardButtonObject &operator =(const KeyboardButton &b);
    bool operator ==(const KeyboardButton &b) const;

Q_SIGNALS:
    void coreChanged();
    void classTypeChanged();
    void dataChanged();
    void flagsChanged();
    void queryChanged();
    void samePeerChanged();
    void textChanged();
    void urlChanged();

private Q_SLOTS:

private:
    KeyboardButton m_core;
};

#endif // LQTG_TYPE_KEYBOARDBUTTON_OBJECT
