// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_LABELEDPRICE_OBJECT
#define LQTG_TYPE_LABELEDPRICE_OBJECT

#include "telegramtypeqobject.h"
#include "telegram/types/labeledprice.h"

#include <QPointer>

class LIBQTELEGRAMSHARED_EXPORT LabeledPriceObject : public TelegramTypeQObject
{
    Q_OBJECT
    Q_ENUMS(LabeledPriceClassType)
    Q_PROPERTY(qint64 amount READ amount WRITE setAmount NOTIFY amountChanged)
    Q_PROPERTY(QString label READ label WRITE setLabel NOTIFY labelChanged)
    Q_PROPERTY(LabeledPrice core READ core WRITE setCore NOTIFY coreChanged)
    Q_PROPERTY(quint32 classType READ classType WRITE setClassType NOTIFY classTypeChanged)

public:
    enum LabeledPriceClassType {
        TypeLabeledPrice
    };

    LabeledPriceObject(const LabeledPrice &core, QObject *parent = 0);
    LabeledPriceObject(QObject *parent = 0);
    virtual ~LabeledPriceObject();

    void setAmount(qint64 amount);
    qint64 amount() const;

    void setLabel(const QString &label);
    QString label() const;

    void setClassType(quint32 classType);
    quint32 classType() const;

    void setCore(const LabeledPrice &core);
    LabeledPrice core() const;

    LabeledPriceObject &operator =(const LabeledPrice &b);
    bool operator ==(const LabeledPrice &b) const;

Q_SIGNALS:
    void coreChanged();
    void classTypeChanged();
    void amountChanged();
    void labelChanged();

private Q_SLOTS:

private:
    LabeledPrice m_core;
};

#endif // LQTG_TYPE_LABELEDPRICE_OBJECT
