// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_PAYMENTSSAVEDINFO_OBJECT
#define LQTG_TYPE_PAYMENTSSAVEDINFO_OBJECT

#include "telegramtypeqobject.h"
#include "telegram/types/paymentssavedinfo.h"

#include <QPointer>
#include "paymentrequestedinfoobject.h"

class LIBQTELEGRAMSHARED_EXPORT PaymentsSavedInfoObject : public TelegramTypeQObject
{
    Q_OBJECT
    Q_ENUMS(PaymentsSavedInfoClassType)
    Q_PROPERTY(qint32 flags READ flags WRITE setFlags NOTIFY flagsChanged)
    Q_PROPERTY(bool hasSavedCredentials READ hasSavedCredentials WRITE setHasSavedCredentials NOTIFY hasSavedCredentialsChanged)
    Q_PROPERTY(PaymentRequestedInfoObject* savedInfo READ savedInfo WRITE setSavedInfo NOTIFY savedInfoChanged)
    Q_PROPERTY(PaymentsSavedInfo core READ core WRITE setCore NOTIFY coreChanged)
    Q_PROPERTY(quint32 classType READ classType WRITE setClassType NOTIFY classTypeChanged)

public:
    enum PaymentsSavedInfoClassType {
        TypePaymentsSavedInfo
    };

    PaymentsSavedInfoObject(const PaymentsSavedInfo &core, QObject *parent = 0);
    PaymentsSavedInfoObject(QObject *parent = 0);
    virtual ~PaymentsSavedInfoObject();

    void setFlags(qint32 flags);
    qint32 flags() const;

    void setHasSavedCredentials(bool hasSavedCredentials);
    bool hasSavedCredentials() const;

    void setSavedInfo(PaymentRequestedInfoObject* savedInfo);
    PaymentRequestedInfoObject* savedInfo() const;

    void setClassType(quint32 classType);
    quint32 classType() const;

    void setCore(const PaymentsSavedInfo &core);
    PaymentsSavedInfo core() const;

    PaymentsSavedInfoObject &operator =(const PaymentsSavedInfo &b);
    bool operator ==(const PaymentsSavedInfo &b) const;

Q_SIGNALS:
    void coreChanged();
    void classTypeChanged();
    void flagsChanged();
    void hasSavedCredentialsChanged();
    void savedInfoChanged();

private Q_SLOTS:
    void coreSavedInfoChanged();

private:
    QPointer<PaymentRequestedInfoObject> m_savedInfo;
    PaymentsSavedInfo m_core;
};

#endif // LQTG_TYPE_PAYMENTSSAVEDINFO_OBJECT
